import tkinter as tk

window = tk.Tk()
window.title('Калькулятор')
window.geometry("350x270")
window.resizable(False, False)
button_add = tk.Button(window, text='+', width=10, height=3)
button_add.place(x=270, y=0)
button_add = tk.Button(window, text='-', width=10, height=3)
button_add.place(x=270, y=55)
button_add = tk.Button(window, text='/', width=10, height=3)
button_add.place(x=270, y=110)
button_add = tk.Button(window, text='*', width=10, height=3)
button_add.place(x=270, y=165)
button_add = tk.Button(window, text='=', width=10, height=3)
button_add.place(x=270, y=220)
number1_entry = tk.Entry(window, width=43)
number1_entry.place(x=5, y=10)
number2_entry = tk.Entry(window, width=43)
number2_entry.place(x=5, y=80)
answer_entry = tk.Entry(window, width=43)
answer_entry.place(x=5, y=200)

window.mainloop()
